### PR TITLE
Fix carousel tab index

### LINKED ISSUE #211: [Keyboard Accessibility] Fix Carousel Tab Index
Current: 
https://main--fonterra-fernleaf--hlxsites.hlx.page/en/products/milk-powder-for-whole-family
image

Expected:
https://www.fernleaf.com.my/en/products/milk-powder-for-whole-family.html
image

### PR DESCRIPTION
**Pull request by ujjwal5**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #211 

Test URLs:
- Before: https://main--fonterra-fernleaf--hlxsites.hlx.page/en/products/yogurt
- After: https://211-fix-carousel-tab-index--fonterra-fernleaf--hlxsites.hlx.page/en/products/yogurt

### CODE REVIEW

**Comment by ujjwal5** [comment]
`If an element has a tabindex of 0, it's included in the natural tab order of the page. Elements with tabindex="0" are focused after elements with positive integer values and before elements without a tabindex attribute.`

So even if we specify a certain tabindex value for carousel items then these will take priority from other elements in dom which is not desired. To fix this we will have to give tabindex for all interactive elements which again is not recommended.
So I believe best way would be to just give tabindex as 0 for elements we want to include in default tab keystroke.

**Comment by sselvara** [comment]
@ujjwal5  please refer this pattern for carousel where the tabindex is managed to focus on interactive elements, even tabindex=-1 is used to tackle the tab focus.

https://www.w3.org/WAI/ARIA/apg/patterns/carousel/examples/carousel-2-tablist/#kbd_label

**Comment by ujjwal5** [comment]
> @ujjwal5 please refer this pattern for carousel where the tabindex is managed to focus on interactive elements, even tabindex=-1 is used to tackle the tab focus.
> 
> https://www.w3.org/WAI/ARIA/apg/patterns/carousel/examples/carousel-2-tablist/#kbd_label

Had to re-order scroll right button after scroll left in the dom and hence modified few CSS to make this work.
@sselvara please help in approving the PR.

**Review by sselvara — APPROVED** [review]

**Review by sselvara — APPROVED** [review]

**Comment by asthabh23** [comment]
@sselvara @ujjwal5 
TBT: https://pagespeed.web.dev/analysis/https-211-fix-carousel-tab-index--fonterra-fernleaf--hlxsites-hlx-live-en-products-yogurt/yi0zvrpi9o?form_factor=mobile

**Comment by asthabh23** [comment]
please check factors before merging

**Comment by ujjwal5** [comment]
> please check factors before merging

@asthabh23 Might be a one off case, pagespeed didn't report any performance issue for me : https://pagespeed.web.dev/analysis/https-211-fix-carousel-tab-index--fonterra-fernleaf--hlxsites-hlx-live-en-products-yogurt/t3uqggcrce?form_factor=mobile

**Comment by ujjwal5** [comment]
> please check factors before merging

@asthabh23 Might be a one off case, pagespeed didn't report any performance issue for me : https://pagespeed.web.dev/analysis/https-211-fix-carousel-tab-index--fonterra-fernleaf--hlxsites-hlx-live-en-products-yogurt/t3uqggcrce?form_factor=mobile

**Pull request merged**
