### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by asthabh23**
Test URLs:
- Before: https://main--fonterra-fernleaf--hlxsites.hlx.live/en
- After: https://update-readme--fonterra-fernleaf--hlxsites.hlx.live/en

### CODE REVIEW

**Review by mkbansal1 — CHANGES_REQUESTED** [review]
@asthabh23 Update Preview and live urls with /en path

**Comment by ujjwal5** [comment]
@asthabh23 can you also fix this typo: https://github.com/hlxsites/fonterra-fernleaf/blob/main/tools/sidekick/config.json#L2
@sselvara do you think correcting this typo would break any existing configuration or do we need to fix this anywhere else too.?

**Comment by sselvara** [comment]
> @asthabh23 can you also fix this typo: https://github.com/hlxsites/fonterra-fernleaf/blob/main/tools/sidekick/config.json#L2 @sselvara do you think correcting this typo would break any existing configuration or do we need to fix this anywhere else too.?

@ujjwal5 updating confg.json will do, it will not break anything.

**Comment by asthabh23** [comment]
@mkbansal1 , the urls are updated.. can you please approve this?

**Review by mkbansal1 — APPROVED** [review]

**Pull request merged**
