### PR TITLE
Fix for: column style conflicts in footer, added accessibility support for icons

### LINKED ISSUE #3: Implement and style Footer
- [ ] Desktop version
Screenshot 2023-07-21 at 1 08 29 PM

- [ ] Mobile version
Screenshot 2023-07-21 at 1 08 06 PM

### PR DESCRIPTION
**Pull request by sselvara**
Fix for: 

- column style conflicts in footer, 
- added accessibility properties for social icons, 
- handle code to accommodate if more than  one social media links/icons are added

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #3

Test URLs:
- Before: https://main--fonterra-fernleaf--hlxsites.hlx.page/
- After: https://3-footer--fonterra-fernleaf--hlxsites.hlx.page/footer

### CODE REVIEW

**Comment by mkbansal1** [comment]
@sselvara Noticed some issues in pagespeed report:
https://pagespeed.web.dev/analysis/https-3-footer--fonterra-fernleaf--hlxsites-hlx-page-footer/ybbffvsfc1?utm_source=psi&utm_medium=redirect&form_factor=mobile
image

image

**Review by mkbansal1 — CHANGES_REQUESTED** [review]
Please fix pagespeed issues

**Review by mkbansal1 — APPROVED** [review]
Please avoid my previous comments, i checked on home page and footer seems good.
https://pagespeed.web.dev/analysis/https-3-footer--fonterra-fernleaf--hlxsites-hlx-page-en/a6h6qiyo86?form_factor=mobile

**Comment by asthabh23** [comment]
@mkbansal1 @sselvara 
I just saw the footer doc, we don't really need a columns block for the footer content. I would prefer adding cell contents as normal text separated by (---) in the footer and the rest should be handled at CSS level.
Please fix this accordingly.

**Comment by sselvara** [comment]
@mkbansal1 

> @sselvara Noticed some issues in pagespeed report: https://pagespeed.web.dev/analysis/https-3-footer--fonterra-fernleaf--hlxsites-hlx-page-footer/ybbffvsfc1?utm_source=psi&utm_medium=redirect&form_factor=mobile image
> 
> image

@mkbansal1, this should be ignored as the footer markup inside the main doesn't render <footer > wrapper in my perspective.

**Pull request merged**
