### PR TITLE
Fixed keyboard issues

### LINKED ISSUE #210: [Keyboard Accessibility] Product listing page focus effect
Current: 
https://main--fonterra-fernleaf--hlxsites.hlx.page/en/products
image
image

Expected:
https://www.fernleaf.com.my/en/products.html
image
image

### PR DESCRIPTION
**Pull request by sselvara**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #210 

Test URLs:
- Before: https://main--fonterra-fernleaf--hlxsites.hlx.page/
- After: https://215-fullwidth-links--fonterra-fernleaf--hlxsites.hlx.page/drafts/subash/products

#209 : https://215-fullwidth-links--fonterra-fernleaf--hlxsites.hlx.page/en
#213 : https://215-fullwidth-links--fonterra-fernleaf--hlxsites.hlx.page/en/stories-and-tips/5-things-to-make-with-milk-packets
#214: https://215-fullwidth-links--fonterra-fernleaf--hlxsites.hlx.page/en/products/calciyum
#215: https://215-fullwidth-links--fonterra-fernleaf--hlxsites.hlx.page/en/about-us

### CODE REVIEW

**Comment by asthabh23** [comment]
@sselvara ,  there is a blue outline that appears around the in-focus field/item. This is happening across all items of the page
The original site doesn't have that.
also please do check the audit scores for product pages or all pages (in pagespeed) for which we have changes in this PR

**Comment by asthabh23** [comment]
also, for "skip to main content", possibly we could reduce its size?

**Comment by sselvara** [comment]
@asthabh23  we had a black outline which I changed it to lighter color, it is a best practise to have outline for accessibility compliance. https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html
We will validate the pagespeed score.

**Comment by asthabh23** [comment]
sure @sselvara , but on click of items the outline shouldn't appear. That is not giving a good experience. This is happening on product landing page, also I see the same in carousel items for on-click. Can you please check this at your end too?

**Review by noormd08 — APPROVED** [review]

**Comment by ujjwal5** [comment]
@sselvara the corresponding header section gets highlighted whenever we are on a specific page, say home/products. It was happening earlier but not happening now. Can you please check ?

**Comment by sselvara** [comment]
> @sselvara the corresponding header section gets highlighted whenever we are on a specific page, say home/products. It was happening earlier but not happening now. Can you please check ?

@ujjwal5, This is addressed, it is not working for sub pages in the previous version as well.
https://main--fonterra-fernleaf--hlxsites.hlx.page/en/products/calciyum
https://main--fonterra-fernleaf--hlxsites.hlx.page/en/stories-and-tips/5-snack-hacks-for-your-school-aged-child
https://main--fonterra-fernleaf--hlxsites.hlx.page/en/recipes/baked-milk-pudding

It is fixed now
https://215-fullwidth-links--fonterra-fernleaf--hlxsites.hlx.page/en/products/calciyum
https://215-fullwidth-links--fonterra-fernleaf--hlxsites.hlx.page/en/stories-and-tips/5-snack-hacks-for-your-school-aged-child
https://215-fullwidth-links--fonterra-fernleaf--hlxsites.hlx.page/en/recipes/baked-milk-pudding

**Comment by asthabh23** [comment]
As discussed, this PR has many changes which are now segregated in different PRs to track LHS incrementally, should be good to close this PR if all the changes are moved across @sselvara

**Comment by asthabh23** [comment]
Closing this as discussed.

**Pull request closed without merging**
